<a href="https://colab.research.google.com/github/luisantoniounocc/ejemplos/blob/main/EJERCIOS_B%C3%81SICOS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy, librerias de ciencia de datos**

In [5]:
import numpy as np
#pip install numpy

ARRAY DE 1 DIMENSION

In [4]:
array_1d=np.array([10,20,30])
print(array_1d)

[10 20 30]


In [6]:
array_1d

array([10, 20, 30])

ARRAY DE 2 DIMENSIONES

In [7]:
array_2d=np.array([(10,20,30), (50,60,70)])
array_2d

array([[10, 20, 30],
       [50, 60, 70]])

ARRAY DE 3 DIMENSIONES

In [10]:
array_3d=np.array([(10,20,30), (40,50,60), (70,80,90,)], dtype=float)
array_3d

array([[10., 20., 30.],
       [40., 50., 60.],
       [70., 80., 90.]])

ARRAY CON CEROS DE 3 FILAS Y 4 COLUMNAS

In [11]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
print(np.zeros((4,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


ARRAY DE UNOS CON DOS DIMENSIONES DE 4 FILAS Y 5 COLUMNAS

In [13]:
np.ones((2,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

ARRAYS INTERVALOS Y SALTOS

In [27]:
np.arange(11,30,2)

array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

INTERVALOS Y DIVISIONES

In [28]:
np.linspace(0,4,7)

array([0.        , 0.66666667, 1.33333333, 2.        , 2.66666667,
       3.33333333, 4.        ])

ARRAYS CON VALORES DADOS

In [29]:
np.full((3,3),7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

ARRAYS CON MATRIZ IDENTIDAD, DIAGONAL DE UNOS

In [38]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

ARRAY VALORES ALEATORIOS 0-1

In [57]:
np.random.random((4, 4))

array([[0.41097086, 0.04263063, 0.58434008, 0.77564297],
       [0.04094122, 0.81422981, 0.18379974, 0.05178374],
       [0.02897562, 0.95489138, 0.23594815, 0.56763204],
       [0.21359398, 0.19427076, 0.26076649, 0.39647374]])

ARRAY DE NUMEROS VACIOS 4*3

In [58]:
np.empty ((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])