<a href="https://colab.research.google.com/github/luisantoniounocc/ejemplos/blob/main/EJERCIOS_B%C3%81SICOS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy, librerias de ciencia de datos**

In [ ]:
import numpy as np
#pip install numpy

ARRAY DE 1 DIMENSION

In [ ]:
array_1d=np.array([10,20,30])
print(array_1d)

[10 20 30]


In [ ]:
array_1d

array([10, 20, 30])

ARRAY DE 2 DIMENSIONES

In [ ]:
array_2d=np.array([(10,20,30), (50,60,70)])
array_2d

array([[10, 20, 30],
       [50, 60, 70]])

ARRAY DE 3 DIMENSIONES

In [ ]:
array_3d=np.array([(10,20,30), (40,50,60), (70,80,90,)], dtype=float)
array_3d

array([[10., 20., 30.],
       [40., 50., 60.],
       [70., 80., 90.]])

ARRAY CON CEROS DE 3 FILAS Y 4 COLUMNAS

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
print(np.zeros((4,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


ARRAY DE UNOS CON DOS DIMENSIONES DE 4 FILAS Y 5 COLUMNAS

In [ ]:
np.ones((2,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

ARRAYS INTERVALOS Y SALTOS

In [ ]:
np.arange(11,30,2)

array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

INTERVALOS Y DIVISIONES

In [ ]:
np.linspace(0,4,7)

array([0.        , 0.66666667, 1.33333333, 2.        , 2.66666667,
       3.33333333, 4.        ])

ARRAYS CON VALORES DADOS

In [ ]:
np.full((3,3),7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

ARRAYS CON MATRIZ IDENTIDAD, DIAGONAL DE UNOS

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

ARRAY VALORES ALEATORIOS 0-1

In [ ]:
np.random.random((4, 4))

array([[0.41097086, 0.04263063, 0.58434008, 0.77564297],
       [0.04094122, 0.81422981, 0.18379974, 0.05178374],
       [0.02897562, 0.95489138, 0.23594815, 0.56763204],
       [0.21359398, 0.19427076, 0.26076649, 0.39647374]])

ARRAY DE NUMEROS VACIOS 4*3

In [ ]:
np.empty ((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

GRABAR Y CARGAR

In [97]:
#Grabar
np.save('mi_array_3d',array_3d)

In [ ]:
#Cargar
mi_array=np.load('mi_array_3d.npy')
mi_array

array([[10., 20., 30.],
       [40., 50., 60.],
       [70., 80., 90.]])

GRABAR Y CARGAR DE 2D

In [ ]:
#Grabar
np.save('mi_array_2d',array_2d)

In [ ]:
#Cargar
mi_array=np.load('mi_array_2d.npy')
mi_array

array([[10, 20, 30],
       [50, 60, 70]])

GRABAR Y CARGAR FICHEROS DE TEXTO

In [ ]:
#grabar de fichero de texto
np.savetxt('mi_array.txt', array_2d, delimiter=" ")

In [ ]:
#cargar de fichero de texto
np.loadtxt('mi_array.txt')

array([[10., 20., 30.],
       [50., 60., 70.]])

EJERCICIO_01

In [157]:
# Escribir un programa que almacene las asignaturas de un curso (por ejemplo Matemáticas, Física, Química, Historia y Lengua) en una lista y la muestre por pantalla.

asignaturas = ["Matemáticas", "Física", "Química", "Historia", "Lengua"]
asignaturas
np.save("ejercicios_practicos/ejercicio01", asignaturas)


In [158]:
np.load("ejercicios_practicos/ejercicio01.npy")

array(['Matemáticas', 'Física', 'Química', 'Historia', 'Lengua'],
      dtype='<U11')

EJERCICIO_02

In [183]:
asignaturas = ["Matemáticas", "Física", "Química", "Historia", "Lengua"]
np.save("ejercicios_practicos/ejercicio02", asignaturas)

In [185]:
asignaturas = np.load("ejercicios_practicos/ejercicio02.npy", allow_pickle=True)

for asignatura in asignaturas:
    print("Yo estudio", asignatura)

Yo estudio Matemáticas
Yo estudio Física
Yo estudio Química
Yo estudio Historia
Yo estudio Lengua


EJERCICIO_03

In [192]:
asignaturas = ["Matemáticas", "Física", "Química", "Historia", "Lengua"]
notas = []

for asignatura in asignaturas:
    nota = input(f"Introduce la nota de {asignatura}: ")
    notas.append(nota)

datos = (asignaturas, notas)
np.save("ejercicios_practicos/ejercicio03", datos)


Introduce la nota de Matemáticas: 44
Introduce la nota de Física: 5
Introduce la nota de Química: 6
Introduce la nota de Historia: 7
Introduce la nota de Lengua: 8


In [193]:
asignaturas, notas = np.load("ejercicios_practicos/ejercicio03.npy", allow_pickle=True)

for asignatura, nota in zip(asignaturas, notas):
    print(f"En {asignatura} has sacado {nota}")


En Matemáticas has sacado 44
En Física has sacado 5
En Química has sacado 6
En Historia has sacado 7
En Lengua has sacado 8


EJERCICIO_04

In [195]:
numeros = []

for i in range(6):
    num = int(input(f"Introduce el número ganador {i+1}: "))
    numeros.append(num)

numeros.sort()

np.save("ejercicios_practicos/ejercicio04", numeros)

Introduce el número ganador 1: 5
Introduce el número ganador 2: 9
Introduce el número ganador 3: 8
Introduce el número ganador 4: 6
Introduce el número ganador 5: 1
Introduce el número ganador 6: 5


In [196]:
numeros = np.load("ejercicios_practicos/ejercicio04.npy")

print("Números ganadores ordenados:")
for numero in numeros:
    print(numero)


Números ganadores ordenados:
1
5
5
6
8
9
