<a href="https://colab.research.google.com/github/luisantoniounocc/ejemplos/blob/main/EJERCICIOS_B%C3%81SICOS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy, librerias de ciencia de datos**

In [ ]:
import numpy as np
#pip install numpy

ARRAY DE 1 DIMENSION

In [ ]:
array_1d=np.array([10,20,30])
print(array_1d)

[10 20 30]


In [ ]:
array_1d

array([10, 20, 30])

ARRAY DE 2 DIMENSIONES

In [ ]:
array_2d=np.array([(10,20,30), (50,60,70)])
array_2d

array([[10, 20, 30],
       [50, 60, 70]])

ARRAY DE 3 DIMENSIONES

In [ ]:
array_3d=np.array([(10.6,20,30), (40,50,60), (70,80,90,)], dtype=float)
array_3d

array([[10.6, 20. , 30. ],
       [40. , 50. , 60. ],
       [70. , 80. , 90. ]])

ARRAY CON CEROS DE 3 FILAS Y 4 COLUMNAS

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
print(np.zeros((4,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


ARRAY DE UNOS CON DOS DIMENSIONES DE 4 FILAS Y 5 COLUMNAS

In [ ]:
np.ones((2,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

ARRAYS INTERVALOS Y SALTOS

In [ ]:
np.arange(11,30,2)

array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

INTERVALOS Y DIVISIONES

In [ ]:
np.linspace(0,4,7)

array([0.        , 0.66666667, 1.33333333, 2.        , 2.66666667,
       3.33333333, 4.        ])

ARRAYS CON VALORES DADOS

In [ ]:
np.full((3,3),7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

ARRAYS CON MATRIZ IDENTIDAD, DIAGONAL DE UNOS

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

ARRAY VALORES ALEATORIOS 0-1

In [ ]:
np.random.random((4, 4))

array([[0.18019012, 0.57934991, 0.10446754, 0.87497139],
       [0.1888319 , 0.07148079, 0.58187479, 0.19294967],
       [0.79654979, 0.27573776, 0.27559266, 0.67237288],
       [0.92803715, 0.28736633, 0.22206788, 0.45245475]])

ARRAY DE NUMEROS VACIOS 4*3

In [ ]:
np.empty ((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

GRABAR Y CARGAR

In [ ]:
#Grabar
np.save('mi_array_3d',array_3d)

In [ ]:
#Cargar
mi_array=np.load('mi_array_3d.npy')
mi_array

array([[10., 20., 30.],
       [40., 50., 60.],
       [70., 80., 90.]])

GRABAR Y CARGAR DE 2D

In [ ]:
#Grabar
np.save('mi_array_2d',array_2d)

In [ ]:
#Cargar
mi_array=np.load('mi_array_2d.npy')
mi_array

array([[10, 20, 30],
       [50, 60, 70]])

GRABAR Y CARGAR FICHEROS DE TEXTO

In [ ]:
#grabar de fichero de texto
np.savetxt('mi_array.txt', array_2d, delimiter=" ")

In [ ]:
#cargar de fichero de texto
np.loadtxt('mi_array.txt')

array([[10., 20., 30.],
       [50., 60., 70.]])

EJERCICIO_01

In [ ]:
# Escribir un programa que almacene las asignaturas de un curso (por ejemplo Matemáticas, Física, Química, Historia y Lengua) en una lista y la muestre por pantalla.

asignaturas = ["Matemáticas", "Física", "Química", "Historia", "Lengua"]
asignaturas
np.save("ejercicios_practicos/ejercicio01", asignaturas)


In [ ]:
np.load("ejercicios_practicos/ejercicio01.npy")

array(['Matemáticas', 'Física', 'Química', 'Historia', 'Lengua'],
      dtype='<U11')

EJERCICIO_02

In [ ]:
asignaturas = ["Matemáticas", "Física", "Química", "Historia", "Lengua"]
np.save("ejercicios_practicos/ejercicio02", asignaturas)

In [ ]:
asignaturas = np.load("ejercicios_practicos/ejercicio02.npy", allow_pickle=True)

for asignatura in asignaturas:
    print("Yo estudio", asignatura)

Yo estudio Matemáticas
Yo estudio Física
Yo estudio Química
Yo estudio Historia
Yo estudio Lengua


EJERCICIO_03

In [ ]:
asignaturas = ["Matemáticas", "Física", "Química", "Historia", "Lengua"]
notas = []

for asignatura in asignaturas:
    nota = input(f"Introduce la nota de {asignatura}: ")
    notas.append(nota)

datos = (asignaturas, notas)
np.save("ejercicios_practicos/ejercicio03", datos)


Introduce la nota de Matemáticas: 4
Introduce la nota de Física: 4
Introduce la nota de Química: 5
Introduce la nota de Historia: 6
Introduce la nota de Lengua: 7


In [ ]:
asignaturas, notas = np.load("ejercicios_practicos/ejercicio03.npy", allow_pickle=True)

for asignatura, nota in zip(asignaturas, notas):
    print(f"En {asignatura} has sacado {nota}")


En Matemáticas has sacado 4
En Física has sacado 4
En Química has sacado 5
En Historia has sacado 6
En Lengua has sacado 7


EJERCICIO_04

In [ ]:
numeros = []

for i in range(6):
    num = int(input(f"Introduce el número ganador {i+1}: "))
    numeros.append(num)

numeros.sort()

np.save("ejercicios_practicos/ejercicio04", numeros)

Introduce el número ganador 1: 1
Introduce el número ganador 2: 5
Introduce el número ganador 3: 5
Introduce el número ganador 4: 6
Introduce el número ganador 5: 8
Introduce el número ganador 6: 8


In [ ]:
numeros = np.load("ejercicios_practicos/ejercicio04.npy")

print("Números ganadores ordenados:")
for numero in numeros:
    print(numero)


Números ganadores ordenados:
1
5
5
6
8
8


EJERCICIO_05

In [ ]:
import numpy as np

numeros = np.arange(1, 11)
np.savetxt('ejercicios_practicos/ejercicio05.npy', numeros, fmt='%d')
print("Números grabados correctamente.")


Números grabados correctamente.


In [ ]:
import numpy as np
n = np.loadtxt('ejercicios_practicos/ejercicio05.npy', dtype=int)[::-1]
print(', '.join(map(str, n)))


10, 9, 8, 7, 6, 5, 4, 3, 2, 1


EJERCICIO_06

In [ ]:


a = ['Matemáticas', 'Física', 'Química', 'Historia', 'Lengua']
n = [float(input(f"{x}: ")) for x in a]
np.save('ejercicios_practicos/ejercicio06.npy', [a, n])


Matemáticas: 4
Física: 12
Química: 7
Historia: 4
Lengua: 7


In [ ]:

a, n = np.load('ejercicios_practicos/ejercicio06.npy', allow_pickle=True)
r = [x for x, y in zip(a, n) if float(y) < 10]
print("Tienes que repetir:", ', '.join(r))


Tienes que repetir: Matemáticas, Química, Historia, Lengua


EJERCICIO_07


In [ ]:
import numpy as np
import string
l = list(string.ascii_lowercase)
r = [x for i, x in enumerate(l, 1) if i % 3 != 0]
np.save('ejercicios_practicos/ejercicio07.npy', r)



In [ ]:

import numpy as np
l = np.load('ejercicios_practicos/ejercicio07.npy', allow_pickle=True)
print(list(l))


[np.str_('a'), np.str_('b'), np.str_('d'), np.str_('e'), np.str_('g'), np.str_('h'), np.str_('j'), np.str_('k'), np.str_('m'), np.str_('n'), np.str_('p'), np.str_('q'), np.str_('s'), np.str_('t'), np.str_('v'), np.str_('w'), np.str_('y'), np.str_('z')]


EJERCICIO_08


In [ ]:

palabra = input("Ingresa una palabra: ").lower()
np.save('ejercicios_practicos/ejercicio08.npy', [palabra])

Ingresa una palabra: 4


In [ ]:

palabra = np.load('ejercicios_practicos/ejercicio08.npy', allow_pickle=True)[0]
print("Es un palíndromo" if palabra == palabra[::-1] else "No es un palíndromo")


Es un palíndromo


EJERCICIO_09

In [ ]:
import numpy as np
p = input("Ingresa una palabra: ").lower()
np.save('ejercicios_practicos/ejercicio09.npy', [p])


Ingresa una palabra: 4


In [ ]:
import numpy as np
p = np.load('ejercicios_practicos/ejercicio09.npy', allow_pickle=True)[0]
for v in 'aeiou':
    print(f"{v}: {p.count(v)}")


a: 0
e: 0
i: 0
o: 0
u: 0


EJERCICIO_10

In [ ]:
import numpy as np
precios = [50, 75, 46, 22, 80, 65, 8]
np.save('ejercicios_practicos/ejercicio10.npy', precios)


In [ ]:
import numpy as np
precios = np.load('ejercicios_practicos/ejercicio10.npy')
print("Menor precio:", min(precios))
print("Mayor precio:", max(precios))


Menor precio: 8
Mayor precio: 80


EJERCICIO_11


In [ ]:
import numpy as np
v1 = [1, 2, 3]
v2 = [-1, 0, 2]
np.save('ejercicios_practicos/ejercicio11.npy', [v1, v2])


In [ ]:
import numpy as np
v1, v2 = np.load('ejercicios_practicos/ejercicio11.npy', allow_pickle=True)
producto = sum(a * b for a, b in zip(v1, v2))
print("Producto escalar:", producto)


Producto escalar: 5


EJERCICIO_12


In [ ]:
import numpy as np
A = [[1, 2], [3, 4]]
B = [[2, 0], [1, 2]]
np.save('ejercicios_practicos/ejercicio12.npy', [A, B])


In [ ]:
import numpy as np
A, B = np.load('ejercicios_practicos/ejercicio12.npy', allow_pickle=True)
resultado = np.matmul(A, B)
print("Producto de matrices:")
print(resultado)


Producto de matrices:
[[ 4  4]
 [10  8]]


EJERCICIO_13


In [ ]:
import numpy as np
entrada = input("Ingresa números separados por comas: ")
numeros = [float(x) for x in entrada.split(',')]
np.save('ejercicios_practicos/ejercicio13.npy', numeros)


Ingresa números separados por comas: 10,60,70


In [ ]:
import numpy as np
numeros = np.load('ejercicios_practicos/ejercicio13.npy')
media = np.mean(numeros)
desviacion = np.std(numeros)
print("Media:", media)
print("Desviación típica:", desviacion)


Media: 46.666666666666664
Desviación típica: 26.246692913372705


TIPOS DE DATOS


In [ ]:
#ENTEROS
np.int64


numpy.int64

In [ ]:
#Decimal, flotantes
np.float64

numpy.float64

In [ ]:
#cpmplejos
np.complex64

numpy.complex64

In [ ]:
#boleanos
np.bool_

numpy.bool

In [ ]:
#objetos
np.object_

numpy.object_

In [ ]:
#cadenas de texto
np.strings

<module 'numpy.strings' from '/usr/local/lib/python3.11/dist-packages/numpy/strings/__init__.py'>

In [ ]:
#formatos
np.bytes_

numpy.bytes_

PROPIEDADES Y CARACTERISTICAS DE ENTORNOS

In [ ]:
array_3d

array([[10.6, 20. , 30. ],
       [40. , 50. , 60. ],
       [70. , 80. , 90. ]])

In [ ]:
array_3d.shape

(3, 3)

In [ ]:
#longitud
len(array_3d)

3

In [ ]:
#numero de dimensiones
array_3d.ndim

2

In [ ]:
array_3d=np.array([(10,20,30), (40,50,60), (70,80,90,)], dtype=float)
array_3d

array([[10., 20., 30.],
       [40., 50., 60.],
       [70., 80., 90.]])

In [ ]:
#numero de dimensiones
array_3d.ndim

2

In [ ]:
#tipos de datos
array_3d.dtype

dtype('float64')

In [ ]:
array_3d.dtype.name

'float64'

In [ ]:
#convertir de un tipo a otro tipo de dato
array_3d.astype(int)

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

OPERADORES MATEMATICOS

In [ ]:
array_1d

array([10, 20, 30])

In [ ]:
#array de ejemplos
array1=np.random.random((4,4))
array1

array([[0.81252445, 0.15849393, 0.6312526 , 0.60037206],
       [0.53314766, 0.26553936, 0.37819197, 0.26952405],
       [0.251989  , 0.34649771, 0.62560801, 0.78590738],
       [0.33783912, 0.8262931 , 0.97522746, 0.96301305]])

In [ ]:
#array 2
array2=np.random.random((4,4))
array2

array([[0.28043203, 0.31749901, 0.21967925, 0.6636258 ],
       [0.06734644, 0.96870181, 0.32841055, 0.60567801],
       [0.14291466, 0.73092618, 0.66272045, 0.91203214],
       [0.92790241, 0.57801421, 0.30857166, 0.94265486]])

In [ ]:
#array 3
array3=np.random.random((4,4))
array3

array([[0.84155466, 0.75627077, 0.59819228, 0.75823243],
       [0.4705259 , 0.65724271, 0.95119315, 0.88515777],
       [0.04066116, 0.0738565 , 0.37229254, 0.67518823],
       [0.81514769, 0.40070185, 0.24735535, 0.36069776]])

In [ ]:
#suma
array4=(array1+array2+array3)
array4

array([[1.62504891, 0.31698786, 1.2625052 , 1.20074413],
       [1.06629533, 0.53107873, 0.75638394, 0.53904811],
       [0.50397801, 0.69299542, 1.25121602, 1.57181477],
       [0.67567824, 1.6525862 , 1.95045491, 1.9260261 ]])

In [ ]:
#otra forma de sumar
array4=np.add(array1, array2, array3)
array4

array([[1.09295648, 0.47599294, 0.85093186, 1.26399787],
       [0.6004941 , 1.23424117, 0.70660252, 0.87520206],
       [0.39490367, 1.07742389, 1.28832846, 1.69793952],
       [1.26574153, 1.40430731, 1.28379912, 1.90566791]])

In [ ]:
#resta
array4=array1-array2-array3
array4

array([[ 0.30423454, -0.20932675,  0.27290025, -0.46167613],
       [ 0.42989563, -0.96039091, -0.07442081, -0.49939875],
       [ 0.07306142, -0.63769272, -0.45171566, -0.84289755],
       [-0.90354502, -0.22933027,  0.36572823, -0.88743073]])

In [ ]:
#resta de otra forma
array4=np.subtract(array1, array2, array3)
array4

array([[ 0.53209243, -0.15900509,  0.41157335, -0.06325374],
       [ 0.46580122, -0.70316245,  0.04978142, -0.33615396],
       [ 0.10907434, -0.38442847, -0.03711244, -0.12612476],
       [-0.59006329,  0.24827889,  0.66665579,  0.0203582 ]])

In [ ]:
#multiplicacion
array4=np.multiply(array1,array2,array3)
array4

array([[0.22785788, 0.05032167, 0.1386731 , 0.39842239],
       [0.0359056 , 0.25722846, 0.12420223, 0.16324479],
       [0.03601292, 0.25326425, 0.41460322, 0.71677279],
       [0.31348173, 0.47760916, 0.30092756, 0.90778893]])

In [ ]:
#division
array4=np.divide(array1,array2)
array4

array([[2.89740247, 0.49919502, 2.87351942, 0.90468463],
       [7.91649375, 0.27411879, 1.15158289, 0.44499561],
       [1.76321308, 0.47405295, 0.94399985, 0.86171018],
       [0.36408906, 1.42953769, 3.16045694, 1.02159666]])

In [ ]:
#exponentes
np.exp(array1)

array([[2.2535899 , 1.17174481, 1.87996395, 1.82279687],
       [1.7042884 , 1.30413419, 1.45964312, 1.30934113],
       [1.28658189, 1.41410625, 1.86938221, 2.1943972 ],
       [1.40191494, 2.28483338, 2.65177031, 2.61957752]])

In [ ]:
#seno
np.sin(array1)

array([[0.72602547, 0.15783119, 0.59015643, 0.56494951],
       [0.50824666, 0.26242976, 0.36924081, 0.2662727 ],
       [0.24933064, 0.33960575, 0.58559024, 0.70746676],
       [0.33144913, 0.73542461, 0.82782951, 0.82091589]])

In [ ]:
#coseno
np.cos(array1)

array([[0.68766781, 0.98746611, 0.80728891, 0.82512548],
       [0.86121155, 0.9649511 , 0.92933375, 0.96389774],
       [0.96841842, 0.94056788, 0.81060723, 0.70674662],
       [0.94347309, 0.67760655, 0.56097977, 0.57104912]])

In [ ]:
#logaritmo
log_array=np.log(array3)
array3

array([[0.22785788, 0.05032167, 0.1386731 , 0.39842239],
       [0.0359056 , 0.25722846, 0.12420223, 0.16324479],
       [0.03601292, 0.25326425, 0.41460322, 0.71677279],
       [0.31348173, 0.47760916, 0.30092756, 0.90778893]])

COMPARACIONES ENTRE MATRICES

In [ ]:
#==
array1==array2

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
# <
array1

array([[0.81252445, 0.15849393, 0.6312526 , 0.60037206],
       [0.53314766, 0.26553936, 0.37819197, 0.26952405],
       [0.251989  , 0.34649771, 0.62560801, 0.78590738],
       [0.33783912, 0.8262931 , 0.97522746, 0.96301305]])

In [ ]:
array1<0.5

array([[False,  True, False, False],
       [False,  True,  True,  True],
       [ True,  True, False, False],
       [ True, False, False, False]])

In [ ]:
# <= / >=
array2

array([[0.28043203, 0.31749901, 0.21967925, 0.6636258 ],
       [0.06734644, 0.96870181, 0.32841055, 0.60567801],
       [0.14291466, 0.73092618, 0.66272045, 0.91203214],
       [0.92790241, 0.57801421, 0.30857166, 0.94265486]])

In [ ]:
array2 <=0.4

array([[ True,  True,  True, False],
       [ True, False,  True, False],
       [ True, False, False, False],
       [False, False,  True, False]])

ESTADISTICAS Y FUNCIONES

In [ ]:
array6 = np.random.random((5,5))
array6

array([[0.22212586, 0.86281654, 0.45456303, 0.43554195, 0.0493364 ],
       [0.44013869, 0.28730358, 0.92355104, 0.8421582 , 0.6612791 ],
       [0.43646056, 0.55537306, 0.26195199, 0.07043065, 0.77284393],
       [0.64671934, 0.47601812, 0.61215351, 0.50737336, 0.93038421],
       [0.9127247 , 0.95458748, 0.18843794, 0.81396179, 0.00351559]])

In [ ]:
#suma de elementos
sumatotal=array6.sum()
print(sumatotal)

13.321750625034547


In [ ]:
#valor mínimo y máximo
array6.min()

np.float64(0.003515591357956205)

In [ ]:
#maximo por fila o columna
array6.max(axis=0)

array([0.9127247 , 0.95458748, 0.92355104, 0.8421582 , 0.93038421])

In [ ]:
#fila acumulada
array6.cumsum(axis=1)

array([[0.22212586, 1.0849424 , 1.53950543, 1.97504738, 2.02438377],
       [0.44013869, 0.72744227, 1.6509933 , 2.49315151, 3.1544306 ],
       [0.43646056, 0.99183362, 1.25378562, 1.32421627, 2.0970602 ],
       [0.64671934, 1.12273746, 1.73489097, 2.24226433, 3.17264854],
       [0.9127247 , 1.86731218, 2.05575012, 2.86971192, 2.87322751]])

In [ ]:
#media
np.mean(array6)

np.float64(0.5328700250013818)

In [ ]:
#mediana
np.median(array6)

np.float64(0.507373362960287)

In [ ]:
#desviacion estandar
np.std(array6)

np.float64(0.2914994255863974)