<a href="https://colab.research.google.com/github/luisantoniounocc/ejemplos/blob/main/EJERCIOS_B%C3%81SICOS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy, librerias de ciencia de datos**

In [65]:
import numpy as np
#pip install numpy

ARRAY DE 1 DIMENSION

In [66]:
array_1d=np.array([10,20,30])
print(array_1d)

[10 20 30]


In [67]:
array_1d

array([10, 20, 30])

ARRAY DE 2 DIMENSIONES

In [68]:
array_2d=np.array([(10,20,30), (50,60,70)])
array_2d

array([[10, 20, 30],
       [50, 60, 70]])

ARRAY DE 3 DIMENSIONES

In [69]:
array_3d=np.array([(10,20,30), (40,50,60), (70,80,90,)], dtype=float)
array_3d

array([[10., 20., 30.],
       [40., 50., 60.],
       [70., 80., 90.]])

ARRAY CON CEROS DE 3 FILAS Y 4 COLUMNAS

In [70]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [71]:
print(np.zeros((4,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


ARRAY DE UNOS CON DOS DIMENSIONES DE 4 FILAS Y 5 COLUMNAS

In [72]:
np.ones((2,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

ARRAYS INTERVALOS Y SALTOS

In [73]:
np.arange(11,30,2)

array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

INTERVALOS Y DIVISIONES

In [74]:
np.linspace(0,4,7)

array([0.        , 0.66666667, 1.33333333, 2.        , 2.66666667,
       3.33333333, 4.        ])

ARRAYS CON VALORES DADOS

In [75]:
np.full((3,3),7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

ARRAYS CON MATRIZ IDENTIDAD, DIAGONAL DE UNOS

In [76]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

ARRAY VALORES ALEATORIOS 0-1

In [77]:
np.random.random((4, 4))

array([[0.18019012, 0.57934991, 0.10446754, 0.87497139],
       [0.1888319 , 0.07148079, 0.58187479, 0.19294967],
       [0.79654979, 0.27573776, 0.27559266, 0.67237288],
       [0.92803715, 0.28736633, 0.22206788, 0.45245475]])

ARRAY DE NUMEROS VACIOS 4*3

In [78]:
np.empty ((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

GRABAR Y CARGAR

In [79]:
#Grabar
np.save('mi_array_3d',array_3d)

In [80]:
#Cargar
mi_array=np.load('mi_array_3d.npy')
mi_array

array([[10., 20., 30.],
       [40., 50., 60.],
       [70., 80., 90.]])

GRABAR Y CARGAR DE 2D

In [81]:
#Grabar
np.save('mi_array_2d',array_2d)

In [82]:
#Cargar
mi_array=np.load('mi_array_2d.npy')
mi_array

array([[10, 20, 30],
       [50, 60, 70]])

GRABAR Y CARGAR FICHEROS DE TEXTO

In [83]:
#grabar de fichero de texto
np.savetxt('mi_array.txt', array_2d, delimiter=" ")

In [84]:
#cargar de fichero de texto
np.loadtxt('mi_array.txt')

array([[10., 20., 30.],
       [50., 60., 70.]])

EJERCICIO_01

In [85]:
# Escribir un programa que almacene las asignaturas de un curso (por ejemplo Matemáticas, Física, Química, Historia y Lengua) en una lista y la muestre por pantalla.

asignaturas = ["Matemáticas", "Física", "Química", "Historia", "Lengua"]
asignaturas
np.save("ejercicios_practicos/ejercicio01", asignaturas)


In [86]:
np.load("ejercicios_practicos/ejercicio01.npy")

array(['Matemáticas', 'Física', 'Química', 'Historia', 'Lengua'],
      dtype='<U11')

EJERCICIO_02

In [87]:
asignaturas = ["Matemáticas", "Física", "Química", "Historia", "Lengua"]
np.save("ejercicios_practicos/ejercicio02", asignaturas)

In [88]:
asignaturas = np.load("ejercicios_practicos/ejercicio02.npy", allow_pickle=True)

for asignatura in asignaturas:
    print("Yo estudio", asignatura)

Yo estudio Matemáticas
Yo estudio Física
Yo estudio Química
Yo estudio Historia
Yo estudio Lengua


EJERCICIO_03

In [90]:
asignaturas = ["Matemáticas", "Física", "Química", "Historia", "Lengua"]
notas = []

for asignatura in asignaturas:
    nota = input(f"Introduce la nota de {asignatura}: ")
    notas.append(nota)

datos = (asignaturas, notas)
np.save("ejercicios_practicos/ejercicio03", datos)


Introduce la nota de Matemáticas: 4
Introduce la nota de Física: 4
Introduce la nota de Química: 5
Introduce la nota de Historia: 6
Introduce la nota de Lengua: 7


In [91]:
asignaturas, notas = np.load("ejercicios_practicos/ejercicio03.npy", allow_pickle=True)

for asignatura, nota in zip(asignaturas, notas):
    print(f"En {asignatura} has sacado {nota}")


En Matemáticas has sacado 4
En Física has sacado 4
En Química has sacado 5
En Historia has sacado 6
En Lengua has sacado 7


EJERCICIO_04

In [93]:
numeros = []

for i in range(6):
    num = int(input(f"Introduce el número ganador {i+1}: "))
    numeros.append(num)

numeros.sort()

np.save("ejercicios_practicos/ejercicio04", numeros)

Introduce el número ganador 1: 1
Introduce el número ganador 2: 5
Introduce el número ganador 3: 5
Introduce el número ganador 4: 6
Introduce el número ganador 5: 8
Introduce el número ganador 6: 8


In [94]:
numeros = np.load("ejercicios_practicos/ejercicio04.npy")

print("Números ganadores ordenados:")
for numero in numeros:
    print(numero)


Números ganadores ordenados:
1
5
5
6
8
8


EJERCICIO_05

In [111]:
import numpy as np

numeros = np.arange(1, 11)
np.savetxt('ejercicios_practicos/ejercicio05.npy', numeros, fmt='%d')
print("Números grabados correctamente.")


Números grabados correctamente.


In [113]:
import numpy as np
n = np.loadtxt('ejercicios_practicos/ejercicio05.npy', dtype=int)[::-1]
print(', '.join(map(str, n)))


10, 9, 8, 7, 6, 5, 4, 3, 2, 1


EJERCICIO_06

In [114]:


a = ['Matemáticas', 'Física', 'Química', 'Historia', 'Lengua']
n = [float(input(f"{x}: ")) for x in a]
np.save('ejercicios_practicos/ejercicio06.npy', [a, n])


Matemáticas: 4
Física: 12
Química: 7
Historia: 4
Lengua: 7


In [115]:

a, n = np.load('ejercicios_practicos/ejercicio06.npy', allow_pickle=True)
r = [x for x, y in zip(a, n) if float(y) < 10]
print("Tienes que repetir:", ', '.join(r))


Tienes que repetir: Matemáticas, Química, Historia, Lengua


EJERCICIO_07


In [109]:
import numpy as np
import string
l = list(string.ascii_lowercase)
r = [x for i, x in enumerate(l, 1) if i % 3 != 0]
np.save('ejercicios_practicos/ejercicio07.npy', r)



In [110]:

import numpy as np
l = np.load('ejercicios_practicos/ejercicio07.npy', allow_pickle=True)
print(list(l))


[np.str_('a'), np.str_('b'), np.str_('d'), np.str_('e'), np.str_('g'), np.str_('h'), np.str_('j'), np.str_('k'), np.str_('m'), np.str_('n'), np.str_('p'), np.str_('q'), np.str_('s'), np.str_('t'), np.str_('v'), np.str_('w'), np.str_('y'), np.str_('z')]


EJERCICIO_08


In [107]:

palabra = input("Ingresa una palabra: ").lower()
np.save('ejercicios_practicos/ejercicio08.npy', [palabra])

Ingresa una palabra: 4


In [108]:

palabra = np.load('ejercicios_practicos/ejercicio08.npy', allow_pickle=True)[0]
print("Es un palíndromo" if palabra == palabra[::-1] else "No es un palíndromo")


Es un palíndromo


EJERCICIO_09

In [105]:
import numpy as np
p = input("Ingresa una palabra: ").lower()
np.save('ejercicios_practicos/ejercicio09.npy', [p])


Ingresa una palabra: 4


In [106]:
import numpy as np
p = np.load('ejercicios_practicos/ejercicio09.npy', allow_pickle=True)[0]
for v in 'aeiou':
    print(f"{v}: {p.count(v)}")


a: 0
e: 0
i: 0
o: 0
u: 0


EJERCICIO_10

In [103]:
import numpy as np
precios = [50, 75, 46, 22, 80, 65, 8]
np.save('ejercicios_practicos/ejercicio10.npy', precios)


In [104]:
import numpy as np
precios = np.load('ejercicios_practicos/ejercicio10.npy')
print("Menor precio:", min(precios))
print("Mayor precio:", max(precios))


Menor precio: 8
Mayor precio: 80


EJERCICIO_11


In [101]:
import numpy as np
v1 = [1, 2, 3]
v2 = [-1, 0, 2]
np.save('ejercicios_practicos/ejercicio11.npy', [v1, v2])


In [102]:
import numpy as np
v1, v2 = np.load('ejercicios_practicos/ejercicio11.npy', allow_pickle=True)
producto = sum(a * b for a, b in zip(v1, v2))
print("Producto escalar:", producto)


Producto escalar: 5


EJERCICIO_12


In [99]:
import numpy as np
A = [[1, 2], [3, 4]]
B = [[2, 0], [1, 2]]
np.save('ejercicios_practicos/ejercicio12.npy', [A, B])


In [100]:
import numpy as np
A, B = np.load('ejercicios_practicos/ejercicio12.npy', allow_pickle=True)
resultado = np.matmul(A, B)
print("Producto de matrices:")
print(resultado)


Producto de matrices:
[[ 4  4]
 [10  8]]


EJERCICIO_13


In [97]:
import numpy as np
entrada = input("Ingresa números separados por comas: ")
numeros = [float(x) for x in entrada.split(',')]
np.save('ejercicios_practicos/ejercicio13.npy', numeros)


Ingresa números separados por comas: 10,60,70


In [98]:
import numpy as np
numeros = np.load('ejercicios_practicos/ejercicio13.npy')
media = np.mean(numeros)
desviacion = np.std(numeros)
print("Media:", media)
print("Desviación típica:", desviacion)


Media: 46.666666666666664
Desviación típica: 26.246692913372705


TIPOS DE DATOS


In [95]:
#ENTEROS
np.int64


numpy.int64

In [96]:
#Decimal, flotantes
np.float64

numpy.float64

In [117]:
#cpmplejos
np.complex64

numpy.complex64

In [120]:
#boleanos
np.bool_

numpy.bool

In [121]:
#objetos
np.object_

numpy.object_

In [123]:
#cadenas de texto
np.strings

<module 'numpy.strings' from '/usr/local/lib/python3.11/dist-packages/numpy/strings/__init__.py'>

In [125]:
#formatos
np.bytes_

numpy.bytes_